# Generated by Django 3.0.2 on 2020-04-27 15:14

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_accounts_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='Phone_Num',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
