# Generated by Django 3.0.2 on 2020-04-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_auto_20200427_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='Phone_Num',
            field=models.BigIntegerField(unique=True),
        ),
    ]
