# Generated by Django 3.0.2 on 2020-05-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_auto_20200427_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phonenumber', models.CharField(max_length=10)),
                ('alt_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=800)),
                ('landmark', models.CharField(max_length=300)),
                ('ordered', models.FileField(upload_to='Orders/ordered')),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
