# Generated by Django 3.0.2 on 2020-05-16 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
