# Generated by Django 3.0.2 on 2020-05-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_delete_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Super',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phonenumber', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='alt_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
