# Generated by Django 3.0.2 on 2020-06-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_auto_20200531_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.BooleanField(null=True),
        ),
    ]
